# Title of the page
title: "Brief History of Neurotechnology"
# Your name
author: NTMC
# Show a link to LinkedIn in the header intro. Comment out to disable.
linkedin: https://www.linkedin.com/company/neurotechmc/about/
# Show a link at the top of your timeline to your main personal site
# Comment this out to disable
personal_site:
  url: https://neurotechmicrocreds.com/
  #title: neil.gg
# show today marker at end of timeline
#show_today: true

# Your timeline is split into periods (e.g., decades, childhood/teens/adult, "Before Timeliner"/"After Timeliner", etc)
# Each period has a list of events formatted as `- date: title`. If you don't want to have period dividers, leave out the name field.
periods:
  - name: Magnetic Resonance Imaging (MRI)
    events:
    - 1938: >-
        <b>Isidor Isaac Rabi</b> first detects the phenomenon of nuclear magnetic resonance (NMR), the underlying principles used in MRI,
        in a beam of lithium chloride through a complex experimental procedure 
        <a href="https://doi.org/10.1103/PhysRev.53.318" target="_blank" rel="noopener">(Link to original paper)</a>.
    - 1946: "<b>Felix Bloch</b> & <b>Edward Mills Purcell</b> extend the work done by <b>Rabi</b> by developing new methods for obtaining precise measurements
    from nuclear magnetization in solids and liquids. Bloch & Purcell shared the Nobel Prize in Physics for this work in 1952."
    - 1971: >-
        <b>Raymond Damadian</b> shows MR relaxation time could be used to distinguish cancer from healthy tissue, being the first to identify 
        the clinical use of NMR <a href="https://doi.org/10.1126/science.171.3976.1151" target="_blank" rel="noopener">(Link to original paper)</a>.
    - 1973: >-
        <b>Paul C. Lauterbur</b> develops the theory for MRI by proposing the use of magnetic field gradients to encode spatial information 
        from the NMR signal <a href="https://doi.org/10.1038/242190a0" target="_blank" rel="noopener">(Link to original paper)</a>. 
        He recieved the Nobel Prize in Physiology or Medicine in 2003 jointly with <b>Peter Mansfield</b>.
    - 1974: "<b>Damadian</b> designs and builds the first full-body MRI machine, called 'Indomitable'."
    - 1977: >-
        <b>Damadian</b>, <b>Larry Minkoff</b>, and <b>Michael Goldsmith</b> perform the first MRI scan on a live animal to visualize a tumour
        <a href="https://doi.org/10.1126/science.1006309" target="_blank" rel="noopener">(Link to original paper)</a>, 
        and MRI body scan of a human <a href="https://doi.org/10.1038/270722a0" target="_blank" rel="noopener">(Link to original paper)</a>.
        <br>
        <br>
        <b>Peter Mansfield</b> invents an MRI acquisition method that makes scan times suitable for clinical use, called echo planar imaging (EPI)
        <a href="https://iopscience.iop.org/article/10.1088/0022-3719/10/3/004" target="_blank" rel="noopener">(Link to original paper)</a>. 
        He recieved the Nobel Prize in Physiology or Medicine in 2003 jointly with <b>Lauterbur</b>.
    - 1978: "<b>Damadian</b> founds FONAR corporation, which produced the first commercially available MRI machine in 1980."
    - 1986-1987: "<b>Charles Dumulin</b> & <b>Howard Hart</b> develop MR angiography, where vasculature can be imaged using MRI. 
    Additionally, <b>Denis Le Bihan</b> obtained the first diffusion MR images."
    - 1990: >-
        <b>Seiji Ogawa</b> recognizes deoxyhemoglobin and oxyhemoglobin have different magnetic properties, and discovered the technique that
        underlies functional MRI (fMRI) <a href="https://doi.org/10.1073/pnas.87.24.9868" target="_blank" rel="noopener">(Link to original paper)</a>.
    - 2012: >-
        Animal studies are performed using a magnet strength of 21.1 Tesla <a href="https://doi.org/10.1016%2Fj.jmr.2012.05.016" target="_blank" rel="noopener">(Link to original paper)</a>.
    - 2019: >-
        For the first time, human studies were performed using a magnet strength of 10.5 Tesla
        <a href="https://doi.org/10.1002%2Fmrm.28093" target="_blank" rel="noopener">(Link to original paper)</a>.
    - 2020: >-
        <a href="https://hyperfine.io/" target="_blank" rel="noopener">Hyperfine</a>'s 
        portable MR imaging system becomes the first FDA approved portable MRI system capable of providing neuroimaging at the 
        bedside, eliminating the need for patients to be moved to a specialized MR suite.
    
  - name: X-ray & Computed Tomography (CT)
    events:
    - 1895: >-
        <b>Wilhelm Roentgen</b> finds that cathode rays are able to pass through human tissue and visualize underlying anatomy, 
        giving rise to clinical X-ray imaging or radiography 
        <a href="https://www.aps.org/publications/apsnews/200111/history.cfm" target="_blank" rel="noopener">(Link for more details)</a>. 
        For this work he recieved the Novel Prize in Physics in 1901.
    - 1913: >-
        <b>William David Coolidge</b> designs a high vacuum X-ray tube that was a reliable sources of X-rays and could operate at 
        energies up to 100,000 volts. This work overcame technological issues in previous X-ray tubes that often broke down at high voltages. 
    - 1917: >-
        <b> Johann Radon</b> develops the mathematical theory behind CT by showing an object can be reconstructed based on an infinite set
        of its projections, known as the Radon transform.
    - 1961: >-
        <b>William Oldendorf</b> theorizes the ability to scan a head through the use of a transmitted beam of X-rays in conjunction with the 
        Radon transform, creating an apparatus that has a rotating source and coupled detector that could get X-ray images of various materials.
    - 1967: >-
        <b>Godfrey Newbold Hounsfield</b> extends the theory for CT by taking several X-ray images at different angles followed by computer reconstruction,  
        also inventing the first commercially available CT scanner. For this work he recieved the Nobel Prize in Physiology or Medicine in 1979. 
    - 1971: >-
        In London, England, a CT scanner is used clinically to image a women suspected to have a brain tumour.
        
  - name: Electro- & Magneto-encephalogram (EEG & MEG)
    events:
    - 1849: >-
        <b>Hermann von Helmholtz</b> measures the speed at which electrical impulses are conducted along nerve fibres. 
    - 1875: >-
        <b>Richard Caton</b> measures electrical phenomena from exposed cerebral hemispheres in monkeys. 
    - 1924: >-
        <b>Hans Berger</b> invents the electroencephalogram (EEG) and was the first to record large-scale electrical activity in the brain. 
        The first EEG trace obtained from a human brain was published in 1929
        <a href="http://dx.doi.org/10.1136/jnnp.74.1.9" target="_blank" rel="noopener">(Link to read more)</a>. 
    - 1930s: >-
        <b>Wilder Penfield</b> develops a technique that obtains EEG recordings directly from pial matter in the brain, now known as 
        electrocorticography (ECoG).
    - 1968: >-
        <b>David Cohen</b> discovers magnetoencephalography (MEG)
        <a href="https://www.science.org/doi/10.1126/science.161.3843.784" target="_blank" rel="noopener">(Link for original paper)</a>.
        
  - name: Near-Infrared Spectroscopy (NIRS)
    events:
    - 1876: >-
        <b>Karl von Vierordt</b> observes changes in the spectrum of visible light when it passes through human fingers which were predominated by 
        either oxy- or deoxy-hemoglobin, being the first to demonstrate the potential for a non-invasive method for monitoring tissue oxygenation. 
    - 1930-1939: >-
        Based on findings from <b>von Vierordt</b>, <b>Kramer & Matthes</b> find that near-infrared light can also be used to determine levels 
        of oxy- and deoxy-hemoglobin in human tissue, laying the ground for the discovery of near-infrared spectroscopy (NIRS). 
    - 1977: >-
        <b>Frank Jobsis</b>, known as the pioneer of medical applications of NIRS, theorizes the use of near-infrared light to study brain activity 
        continuously and led to the invention of NIRS
        <a href="https://www.science.org/doi/10.1126/science.929199" target="_blank" rel="noopener">(Link for original paper)</a>.
    - 1985: >-
        The first clinical NIRS studies are conducted on newborns by <b>Jobsis & Brazy</b>
        <a href="https://doi.org/10.1542/peds.75.2.217" target="_blank" rel="noopener">(Link for original paper)</a>,
        and adults by <b>Marco Ferrari</b> 
        <a href="https://pubmed.ncbi.nlm.nih.gov/3008520/" target="_blank" rel="noopener">(Link for original paper)</a>.
    - 1992: >-
        Based on the development of fMRI by <b>Seiji Ogawa</b>, studies carried out by <b>Chance, Kato, Hoshi, and Villringer</b> 
        led to the discovery of functional NIRS (fNIRS). 
    - 1996: >-
        <b>Kleinshmidt</b> carries out the first simultaneous recording of brain activation using both fMRI and fNIRS 
        <a href="https://doi.org/10.1097/00004647-1996090000-00006" target="_blank" rel="noopener">(Link for paper)</a>
        
  - name: Neuroelectronic Recording & Stimulation 
    events:
    - 1963: >-
        <b>Hodgkin & Huxley</b> become the first to use an electrode to record an action potential in an axon.
    - 1937: >-
        Physicians <b>Ugo Carletti & Lucio Bini</b> develop and use electroconvulsive therapy (ECT) that electrically induces a seizure as a 
        treatment for mental illness. In the following decades, this became overused and resulted in public backlash. 
    - 1980: >-
        <b>Merton & Morton</b> develop transcranial electrical stimulation (TES) whereby an electrical current is passed through the skull 
        to stimulate the cortex of the brain
        <a href="https://www.nature.com/articles/285227a0" target="_blank" rel="noopener">(Link for original paper)</a>.
    - 1985: >-
        <b>Anthony Barker</b> develops transcranial magnetic stimulation (TMS), whereby a changing magnetic field is used to induce current 
        in a specific region of the brain. 
    - 1987: >-
        <b>Alim Benabid</b> discovers electrical stimulation of the basal ganglia improves symptoms of Parkinson's disease, the first use of what 
        is now known as deep brain stimulation (DBS). 
    - 1997: >-
        DBS is approved by the FDA for tremors and Parkinson's disease. DBS is now approved in the treatment of dystonia (2003), 
        obsessive-compulsive disorder (OCD)(2009), and epilepsy (2018). 
    - 2008: >-
        TMS is approved by the FDA for treatment of medication-refractory depression. 
  
  - name: Positron Emission Tomography (PET) 
    events:
    - 1911: >-
        <b>George Hevesy</b> demonstrates the use of radioactive isotopes for labelling. For this work he recieved the Nobel Prize in Chemistry in 1943.
    - 1934: >-
        <b>Irene & Frederic Joliot-Curie</b> produce an artificial isotope that could be formed and made safe for humans.
    - 1953: >-
        <b>Gordon Brownell & William Sweet</b> invent and demonstrate the first large-scale use of a positron imaging device, with <b>Brownell</b>
        going on to develop the first positron emission tomography (PET) imaging device in 1972.
    - 1976: >-
        <b>Louis Sokoloff, Alfred Wolf, and Joanna Fowler</b> synthesize 2-[<sup>18</sup>F]fluoro-2-deoxy-D-glucose (FDG), which is used to 
        measure cerebral glucose utilization and is still widely used for PET imaging today. 
       
  - name: Brain-Computer Interfaces (BCI)
    events:
    - 1875: >-
        <b>Richard Caton</b> records the first ever electrical activity in the brain of living rabbits. 
    - 1924: >-
        <b>Hans Berger</b> first measures EEG signals and leads to the identification of alpha and beta brain waves. This discovery was a 
        preclude to the development of brain-computer interfaces (BCIs). 
    - 1961: >-
        Otologist <b>William House</b> implants the first cochlear implant into a patient with sensorineural hearing loss
        (<a href="https://jamanetwork.com/journals/jamaotolaryngology/fullarticle/1688121" target="_blank" rel="noopener">See here for in depth review</a>,
        <a href="https://cdn.jamanetwork.com/ama/content_public/journal/otol/926966/ooa130013f1.png?Expires=1677193244&Signature=GpA9dGi1kqQWZN5SWKQMI4OPB2c~XQ3qNMLyWfod-4d5U5bBEW8mahHovDzsw57RuPR6uAv~5nZDmzUz-yv29I7TyfKpdHnptXBaMVz1F-AuBh8vHosCaEJY69felBljgvse4BXzZ78cDraUjbHntyHKn-szV5hHn03Y1ccshJM5iG7JQ1i9OSvkfWNEwfDhT7BpdmhVcNRF-ZAAMNWCcZa3XytReazuF4HfkgN-~zOpNonV9CaG5t04VZxDw9C9P6S9-bP7OpUF-~AFyhmQNxDegXLW6OytbqtasY~fuf49GwlC4VhTqv~ZZZD5FUaBWdtghNRTowoND8q6mIGmAA__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA" target="_blank" rel="noopener">Image of the first cochlear implant prototype</a>).
    - 1965: >-
        <b>Jose Delgada</b> implants his 'stimoceiver' in a bull's brain and shows that by sending a radio signal to this device, he can stop the bull
        from charging at him. Watch this
        <a href="https://www.youtube.com/watch?v=S051A8doXP0" target="_blank" rel="noopener">video</a>
        to learn more about this wild demonstration.
    - 1968: >-
        <b>Brindley</b> & <b>Lewin</b> demonstrate that direct electrical stimulation of the occipital lobe in a patient with blindness 
        can result in the patient experiencing sensations of light ('phosphenes'), being the first to show the use of a visual cortex implant. They 
        also demonstrate that stimulating specific regions of the visual cortex results in phosphenes in a specific region of the patients visual field 
        <a href="https://doi.org/10.1113/jphysiol.1968.sp008519" target="_blank" rel="noopener">(Link for original paper)</a>.
    - 1969: >-
        <b>Eberhard Fetz</b> conducts an experiment where he shows monkeys can control the deflection of a meter arm through consciously 
        controlling the firing rate of their cortical neurons, being the first to show what is now known as 'neurofeedback'
        <a href="https://www.science.org/doi/abs/10.1126/science.163.3870.955" target="_blank" rel="noopener">(Link for original paper)</a>.
    - 1973: >-
        <b>Jacques Vidal</b> coins the term 'BCI' and produces the first academic papers on the topic
        <a href="https://www.annualreviews.org/doi/10.1146/annurev.bb.02.060173.001105" target="_blank" rel="noopener">(1</a>,
        <a href="https://ieeexplore.ieee.org/document/1454811" target="_blank" rel="noopener">2)</a>. 
        He is now regarded as the inventor of BCI's.
    - 1978: >-
        <b>William Dobelle</b> implants a single-array BCI into a man with adulthood blindness that when accompanied with the use of specialized glasses, 
        allowed the man to see shades of grey within a limited field-of-vision
        <a href="https://www.wired.com/2002/09/vision/" target="_blank" rel="noopener">(Read more)</a>. 
    - 1988: >-
        <b>Philip Kennedy</b> builds the first intra-cortical BCI in monkeys by implanting neurotrophic-cone electrodes. He continued this work 
        in humans and even used himself as a test subject for BCI implantation
        <a href="https://www.wired.com/2016/01/phil-kennedy-mind-control-computer/" target="_blank" rel="noopener">(Read more</a>,
        <a href="https://youtube.com/watch?v=SSFugxgtimc" target="_blank" rel="noopener">Interview)</a>. 
    - 1996: >-
        <b>Mark Humayun</b> is the first to use a retinal implant in humans and demonstrates that electrical stimulation of electrodes implanted on the 
        surface of the retina can evoke phosphenes in patients sufferring from photoreceptor degeneration
        <a href="https://jamanetwork.com/journals/jamaophthalmology/article-abstract/641466" target="_blank" rel="noopener">Interview)</a>. 
    - 1998: >-
        <b>Kennedy & Bakay</b> become the first to implant a BCI in the human brain. The patient suffered from 'locked-in syndrome' and in the years
        following implant surgery he was able to control a computer cursor using his thoughts
        <a href="https://journals.lww.com/neuroreport/Fulltext/1998/06010/Restoration_of_neural_output_from_a_paralyzed.7.aspx" target="_blank" rel="noopener">(Read more)</a>
    - 1999-2000: >-
        <b>Miguel Nicolelis</b> develops and implants a BCI which decodes brain activity in monkeys allowing them to control a robotic arm through thought, 
        being the first to accurately predict movement through recording of neuron ensembles 
        <a href="https://www.nature.com/articles/35042582" target="_blank" rel="noopener">(Link for original paper)</a>. 
    - 2006: >-
        <b>Hochberg</b> reports on the first person with tetraplegia being able to control an artificial hand using an implanted BCI
        <a href="https://www.nature.com/articles/nature04970" target="_blank" rel="noopener">(Link for original paper)</a>. 
        This was the first BrainGate trial that used 
        <a href="https://blackrockneurotech.com/research/utah-array/" target="_blank" rel="noopener">Blackrock's Utah Array</a>.
    - 2021: >-
        <b>Neuralink</b>, founded by <b>Elon Musk</b>, shows that its BCI chip allows monkeys to play video games in real-time solely with their thoughts
        <a href="https://www.businessinsider.com/neuralink-elon-musk-microchips-brains-ai-2021-2" target="_blank" rel="noopener">(Link to read more)</a>.
        <br>
        <br>
        <b>Willett & Moses</b> separately use BCIs implanted in the motor cortex of paralyzed patients to allow them to communicate 15-18 words per 
        minute. Willett did so by recording from neurons active when thinking about writing words 
        <a href="https://www.nature.com/articles/s41586-021-03506-2" target="_blank" rel="noopener">(Link to paper)</a>, 
        Moses did so by recording from neurons active when thinking about vocalizing words 
        <a href="https://www.nejm.org/doi/10/1056/NEJMoa2027540" target="_blank" rel="noopener">(Link to paper)</a>.
        <br>
        <br>
        <b>Synchron</b> becomes the first company to recieve FDA approval to conduct a clinical trial of a permanently implanted BCI that uses 
        endovascular electrodes to record/stimulate neurons from within blood vessels
        <a href="https://synchron.com/technology" target="_blank" rel="noopener">(Learn more)</a>.
    
  - name: General Neuroscience 
    events:
    - Before Christ (BC): >-
        Both <b>Herophilus & Galan</b> propose the brain as the control center of the body and cognition, although they incorrectly believed this was 
        the responsibility of the ventricular system specifically.
    - 1860-1865: >-
        <b>Paul Broca</b> is the first to make progress in the theory of cerebral localization, the belief that different aspects of cognition 
        are localized to certain regions of the brain. This work marked the onset of carefully studying deficits in patients with brain damage 
        of specific regions to determine the regions function. 
    - 1906: >-
        <B>Ramon y Cajal</b>, known as 'The father of Modern Neuroscience', discovers an imaging method called Golgi staining using which he discovered 
        that neurons are the structural units that make up the brain and they are separated by small junctions called synapses through which they
        directionally communicate with other neurons. Based on this work, Cajal and Sherrington were the first to vocalize the 'neuron doctrine', stating 
        the neuron is the structural and functional unit of the nervous system 
        <a href="https://www.nature.com/articles/nrn3962#MOESM9" target="_blank" rel="noopener">(Link for review paper)</a>. 
